### ISSUE TITLE
Adding UNETR Repository 

### ISSUE THREAD

**Issue by ahatamiz** [junyuchen245/Transformer_for_medical_image_analysis#1]
Hi @junyuchen245 , nice collection of transformers for medical imaging. 

We have open-sourced UNETR in the following repository:

https://monai.io/research/unetr-btcv-multi-organ-segmentation

It currently supports multi-organ segmentation task using BTCV dataset, but more segmentation tasks (BRATS, MSD etc.) will be added later.

It's also now part of MONAI and can be directly imported:

https://docs.monai.io/en/latest/_modules/monai/networks/nets/unetr.html

**Comment by junyuchen245** [comment]
Hi @ahatamiz,

Thanks for letting me know! I have updated the description and the link.

Junyu

**Comment by ahatamiz** [comment]
Great. Thanks, Junyu !

Ali
